name: Release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    uses: feronatech/shared-workflows/.github/workflows/go-lib-release.yml@main
    with:
      release-body: |
        **Installation:**
        ```bash
        go get github.com/feronatech/go-aws-logging@v${{ steps.get_version.outputs.version }}
        ```
        **Usage:**
        ```go
        import "github.com/feronatech/go-aws-logging/logging"

        logger := NewLogger("us-east-1", "dev", "myapp")
        ```
